services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-rag
    restart: always
    ports:
      - "16333:6333" # HTTP API & Web UI
      - "16334:6334" # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__ENABLE_TLS=false
